# This workflow will bump the version of convertextract and trigger a build when a new
# version of g2p is built (and a dispatch is sent as a result)

name: G2P trigger

on:
  repository_dispatch:
    types: [ g2p-published ]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: bump
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          current=$(python3 setup.py --version)
          bumped=$( echo $current | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "Bumping from version ${current} to ${bumped}"
          cd convertextract && sed -i -e "s/${current}/${bumped}/g" __init__.py
          echo "::set-env name=bumped::$bumped"
      - name: commit
        run: | 
          git config --local user.email "bot@github.com"
          git config --local user.name "GitHub Action Bot"
          git add .
          git commit -m "chore: bump to ${bumped}"

      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          branch: release
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: trigger release
        run: |
          curl --location --request POST 'https://api.github.com/repos/roedoejet/convertextract/dispatches' \
          --header 'Accept: application/vnd.github.everest-preview+json' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.G2P_PAT }}' \
          --header 'Content-Type: text/plain' \
          --data-raw '{
            "event_type": "release",
            "client_payload": {}
          }'